path_classifiers:
  test:
    - src/*.cpp
    - src/*.h
    - exclude: examples
    - exclude: scripts
    - exclude: docs
queries:
  - exclude: cpp/use-of-goto
extraction:
  cpp:
    prepare:    # Customizable step used by all languages.
      packages:
        - g++-6
    after_prepare:    # Customizable step used by all languages.
      - mkdir -p $LGTM_WORKSPACE/latest-gcc-symlinks
      - ln -s /usr/bin/g++-6 $LGTM_WORKSPACE/latest-gcc-symlinks/g++
      - ln -s /usr/bin/gcc-6 $LGTM_WORKSPACE/latest-gcc-symlinks/gcc
      - export PATH=$LGTM_WORKSPACE/latest-gcc-symlinks:$PATH
    index:    # Customizable step used by all languages.
      build_command:
        - CXX=g++-6 CC=gcc-6 cmake .
        - make faunus

