language: cpp
dist: xenial
sudo: required
group: edge
compiler: clang

matrix:
  include:

  # OSX / Clang
  - os: osx
    env: [CONDA_PY=36] # COMPILER=clang++, CXX=clang++, CC=clang]
  - os: osx
    env: [CONDA_PY=37] # COMPILER=clang++, CXX=clang++, CC=clang]

  # Linux / Clang
  - os: linux
    env: [CONDA_PY=36]  # COMPILER=clang++, CXX=clang++, CC=clang]
  - os: linux
    env: [CONDA_PY=37]  # COMPILER=clang++, CXX=clang++, CC=clang]

install:
  - |
    # conda
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
    bash miniconda.sh -b -p $HOME/miniconda
    export PATH="$HOME/miniconda/bin:$PATH"
    hash -r
    conda config --set always_yes yes --set changeps1 no
    conda config --add channels conda-forge
    conda update -q conda
    conda install conda-build=2 anaconda-client
    conda update -q conda-build

script:
  - |
    cd scripts/
    conda config --set anaconda_upload yes
    conda-build --user teokem --token "${CONDA_UPLOAD_TOKEN}" .
