language: cpp
dist: xenial
sudo: required
group: edge
compiler: clang

addons:
    apt:
        packages:
            - python-ruamel.yaml
            - python-jinja2

matrix:
  include:
  - os: linux
    python: 3.7
  - os: osx
    osx_image: xcode10.2
    python: 3.7

script:
  - |
    cmake .
    make faunus -j
    ./faunus --version
    make unittests -j
    ./unittests
    make pyfaunus -j

