language: cpp
dist: trusty
sudo: required
group: edge

matrix:
  include:

  # OSX / Clang
  - os: osx
    osx_image: xcode9.2

  # Linux / Clang
  - os: linux
    compiler: clang
    env: COMPILER=clang++-5.0
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-5.0']
        packages: ['g++-6', 'clang-5.0']

install:
  - |
    # conda
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
    bash miniconda.sh -b -p $HOME/miniconda
    export PATH="$HOME/miniconda/bin:$PATH"
    hash -r
    conda config --set always_yes yes --set changeps1 no
    conda update -q conda
    conda config --add channels conda-forge
    conda install conda-build anaconda-client

script:
  - if [[ "${COMPILER}" != "" ]]; then export CXX=${COMPILER}; fi
  - $CXX --version
  - uname -a
  - cd scripts/
  - conda-build --user teokem --token "${CONDA_UPLOAD_TOKEN}" .

