sudo:
  - false
dist:
  - trusty
language:
  - c++
addons:
  apt:
    sources:
    - llvm-toolchain-trusty-5.0
    packages:
    - clang-5.0
  env:
    - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
compiler:
  - clang

install:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://cmake.org/files/v3.9/cmake-3.9.6-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    fi
  - cmake --version # https://github.com/boostorg/hana/blob/master/.travis.yml

script:
  - CXX=clang++-5.0 CC=clang-5.0 cmake . -DENABLE_PYTHON=off
  - make faunus
