language: cpp
dist: xenial
sudo: required
group: edge
compiler: clang

python:
    - "3.7"

addons:
    apt:
        packages:
            - python-ruamel.yaml
            - python-jinja2

matrix:
  include:
  - os: linux
    compiler: gcc
  - os: osx
    osx_image: xcode11
    compiler: clang

script:
  - |
    cmake . -DENABLE_OPENMP=off -DCMAKE_BUILD_TYPE=Debug
    make faunus || travis_terminate 1
    ./faunus --version || travis_terminate 1

    if [ "$TRAVIS_OS_NAME" = "linux" ] ; then
        ctest -R minimal || travis_terminate 1

        make pyfaunus || travis_terminate 1
        ctest -R pythontest || travis_terminate 1

        make unittests || travis_terminate 1
        ctest -R unittests || travis_terminate 1
    fi

