language: cpp
dist: xenial
sudo: required
group: edge
compiler: clang

matrix:
  include:

  # Python 3.7
  - os: linux
    env: [CONDA_PY=37]
  - os: osx
    env: [CONDA_PY=37]

  # Python 3.6
  - os: osx
    env: [CONDA_PY=36]
  - os: linux
    env: [CONDA_PY=36]

install:
  - |
    # conda
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
    bash miniconda.sh -b -p $HOME/miniconda
    export PATH="$HOME/miniconda/bin:$PATH"
    hash -r
    conda config --set always_yes yes --set changeps1 no
    conda config --add channels conda-forge/label/gcc7
    conda update -q conda
    conda install conda-build=3 anaconda-client
    conda update -q conda-build

script:
  - |
    cd scripts/
    conda config --set anaconda_upload yes
    conda-build --user teokem --token "${CONDA_UPLOAD_TOKEN}" .
