package:
  name: faunus
  version: "nightly"

source:
  #git_rev: 1.1.0
  git_url: https://github.com/mlund/neofaunus.git

build:
  number: 0

requirements:
  build:
    - librsvg
    - openmpi 1.6.3 # [osx]
    - openmpi 2.1.* # [linux64]
    - ruamel_yaml
    - pandoc >=1.19
    - cmake >=3.9
    - python >=3
    - clangdev >=5
  run:
    - openmpi 1.6.3 # [osx]
    - openmpi 2.1.* # [linux64]
    - ruamel_yaml
    - pygments
    - python >=3

about:
  home: http://mlund.github.io/neofaunus
  license: MIT
