package:
  name: faunus
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_url: https://github.com/mlund/faunus.git

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  script:
    - export CC=clang     # [osx]
    - export CXX=clang++  # [osx]
    - cmake -DENABLE_MPI=on -DENABLE_OPENMP=on -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX:PATH=$PREFIX
    - make faunus -j2
    - cmake -DCMAKE_INSTALL_PREFIX:PATH=$PREFIX # needed to build pyfaunus
    - make pyfaunus -j2
    - make install
    - make tests -j2
    - ctest --output-on-failure

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - llvm-openmp   # [osx]
  host:
    - numpy
    - matplotlib
    - python
    - ruamel_yaml
    - nbconvert
    - notebook
    - jupyter
    - openmpi 1.6.3  # [osx]
    - openmpi 3.1.*  # [linux64]
    - llvm-openmp    # [osx]
  run:
    - llvm-openmp    # [osx]
    - openmpi 1.6.3  # [osx]
    - openmpi 3.1.*  # [linux64]
    - ruamel_yaml
    - pygments
    - numpy
    - python

about:
  home: http://mlund.github.io/faunus
  summary: A Framework for Molecular Monte Carlo Simulations
  license: MIT
  doc_url: http://mlund.github.io/faunus
  dev_url: https://github.com/mlund/faunus
