package:
  name: faunus
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_url: https://github.com/mlund/faunus.git

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  script_env:
    - PATH

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - llvm-openmp
  host:
    - numpy
    - matplotlib
    - python
    - ruamel_yaml
    - nbconvert
    - notebook
    - jupyter
    - openmpi 1.6.3      # [osx]
    - openmpi 3.1.*      # [linux64]
  run:
    - openmpi 1.6.3 # [osx]
    - openmpi 3.1.* # [linux64]
    - ruamel_yaml
    - pygments
    - numpy
    - python

about:
  home: http://mlund.github.io/faunus
  summary: A Framework for Molecular Monte Carlo Simulations
  license: MIT
