package:
  name: faunus
  version: {{ GIT_DESCRIBE_TAG + '_' + GIT_DESCRIBE_NUMBER }}

source:
  git_url: https://github.com/mlund/faunus.git

build:
  number: {{ GIT_DESCRIBE_NUMBER }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
      #- librsvg
    - numpy
    - matplotlib
    - python
    - ruamel_yaml
    - nbconvert
    - notebook
    - jupyter
    - mpich
      #- openmpi 1.6.3      # [osx]
      #- openmpi 3.1.*      # [linux64]
      #- pandoc >=1.19 # [linux64]
  run:
      #- openmpi 1.6.3 # [osx]
      #- openmpi 3.1.* # [linux64]
    - mpich
    - ruamel_yaml
    - pygments
    - numpy
    - python

build:
  script_env:
    - PATH

about:
  home: http://mlund.github.io/faunus
  summary: A Framework for Molecular Monte Carlo Simulations
  license: MIT
