package:
  name: faunus
  version: "nightly"

source:
  #git_rev: 1.1.0
  git_url: https://github.com/mlund/neofaunus.git

build:
  number: 0

requirements:
  build:
    - librsvg
    - cmake >=3.9
    - python >=3
    - ruamel_yaml
    - openmpi 1.6.3      # [osx]
    - openmpi 2.1.*      # [linux64]
    - clangdev >=5       # [linux64]
    #- pandoc >=1.19 # [linux64]
    #- clangdev >=5       # [osx]
    #- clangxx_osx-64 >=4 # [osx]
  run:
    - openmpi 1.6.3 # [osx]
    - openmpi 2.1.* # [linux64]
    - ruamel_yaml
    - pygments
    - python >=3

about:
  home: http://mlund.github.io/neofaunus
  license: MIT
