package:
  name: faunus
  version: {{ GIT_DESCRIBE_TAG }}

about:
  home: http://mlund.github.io/faunus
  summary: A Framework for Molecular Monte Carlo Simulations
  license: MIT
  doc_url: http://mlund.github.io/faunus
  dev_url: https://github.com/mlund/faunus

source:
  git_url: https://github.com/mlund/faunus.git

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - llvm-openmp   # [osx]
    - intel-openmp  # [linux]
  host:
    - numpy
    - matplotlib
    - python
    - ruamel_yaml
    - nbconvert
    - notebook
    - jupyter
    - openmpi 1.6.3 # [osx]
    - openmpi 3.1.* # [linux64]
  run:
    - llvm-openmp   # [osx]
    - intel-openmp  # [linux]
    - openmpi 1.6.3 # [osx]
    - openmpi 3.1.* # [linux64]
    - ruamel_yaml
    - pygments
    - numpy
    - python

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  script_env:
    - PATH
  script:
    - export CC=clang    # [osx]
    - export CXX=clang++ # [osx]
    - cmake -DENABLE_MPI=on -DENABLE_OPENMP=on -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX:PATH=$PREFIX
    - alias make="make -s"
    - make faunus
    - cmake -DCMAKE_INSTALL_PREFIX:PATH=$PREFIX # needed to build pyfaunus
    - make pyfaunus
    - make install
    - make tests
    - ctest --output-on-failure

