package:
  name: faunus
  version: "beta1"

source:
  #git_rev: 1.1.0
  git_url: https://github.com/mlund/neofaunus.git

build:
  number: 0

requirements:
  build:
    - librsvg
    - openmpi
    - ruamel_yaml
    - pandoc
    - cmake
    - clangdev
  run:
    - openmpi
    - ruamel_yaml
    - pygments

about:
  home: http://mlund.github.io/neofaunus
  license: MIT
